# Generated by Django 4.2.19 on 2025-02-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberpayment', '0003_transaction_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
