# Generated by Django 4.2.19 on 2025-03-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberpayment', '0005_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='full_name',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
